export default [
  {
    id: "YB-EK01",
    type: "group",
    name: "辅助",
    ico: "el-icon-video-play",
    children: [
      {
        id: "YB-EK02",
        type: "timer",
        name: "开始",
        ico: "el-icon-time"
      },
      {
        id: "YB-EK03",
        type: "task",
        name: "结束",
        ico: "el-icon-odometer"
      }
    ]
  },

  {
    id: "YB-EK04",
    left: "26px",
    top: "161px",
    type:'group1',
    ico: "el-icon-user-solid",
    show: true,
    name: "前幅",
    children: [
      {
        id: "YB-EK05",
        name: "YB-EK05",
        type:'group1',
        left: "26px",
        top: "161px",
        ico: "el-icon-user-solid",
        show: true,
        tenantSiteCode: "test",
        styleCode: "GA191123A",
        craftNum: "HQFCF0001",
        craftCode: null,
        craftName: "前幅处理工艺一",
        basicCraftName: null,
        categoryCode: "C001",
        componentCode: "YB",
        componentName: "部件测试",
        deviceCode: "MDZ2",
        deviceName: "自动锁螺丝",
        materialMiddleclassCode: "XX0212",
        materialMiddleclassName: "灰黑色",
        toolCode1: "T001",
        toolCode2: "T002",
        toolCode3: "T003",
        toolName1: "T001",
        toolName2: "T002",
        toolName3: "T003",
        salaryLevelCode: "A",
        salaryLevelName: "一般工序",
        hourlyWage: 12.222,
        fabricCoefficient: 1.8,
        bundleTime: 16.3,
        deviceTmu: 12.2,
        artificialTmu: 20.2,
        deviceFloat: 2.3,
        artificialFloat: 5.4,
        manualDeviceTmu: 0,
        manualArtificialTmu: 0,
        bmSecond: 1.2,
        standardTimeTmu: 625.2,
        standardTimeSecond: 22.5,
        standardPrice: 4.581,
        workInstructions: "做工说明",
        qualityRequirements: "品质要求wwwwwwwwww",
        modifyTime: "2019-12-25 11:42:04",
        modifyUserId: "test",
        modifyUserName: "test"
      },
      {
        id: "YB-EK06",
        name: "YB-EK06",
        type:"timer3",
        left: "26px",
        top: "161px",
        ico: "el-icon-user-solid",
        show: true,
        tenantSiteCode: "test",
        styleCode: "GA191123A",
        craftNum: "HQFCF0001",
        craftCode: null,
        craftName: "前幅处理工艺一",
        basicCraftName: null,
        categoryCode: "C001",
        componentCode: "YB",
        componentName: "部件测试",
        deviceCode: "MDZ2",
        deviceName: "自动锁螺丝",
        materialMiddleclassCode: "XX0212",
        materialMiddleclassName: "灰黑色",
        toolCode1: "T001",
        toolCode2: "T002",
        toolCode3: "T003",
        toolName1: "T001",
        toolName2: "T002",
        toolName3: "T003",
        salaryLevelCode: "A",
        salaryLevelName: "一般工序",
        hourlyWage: 12.222,
        fabricCoefficient: 1.8,
        bundleTime: 16.3,
        deviceTmu: 12.2,
        artificialTmu: 20.2,
        deviceFloat: 2.3,
        artificialFloat: 5.4,
        manualDeviceTmu: 0,
        manualArtificialTmu: 0,
        bmSecond: 1.2,
        standardTimeTmu: 625.2,
        standardTimeSecond: 22.5,
        standardPrice: 4.581,
        workInstructions: "做工说明",
        qualityRequirements: "品质要求wwwwwwwwww",
        modifyTime: "2019-12-25 11:42:04",
        modifyUserId: "test",
        modifyUserName: "test"
      }
    ]
  },

  {
    id: 'YB-EK07',
    name: "后幅",
    type:'group2',
    children: [
      {
        id: "YB-EK08",
        name: "YB-EK08",
        left: "26px",
        top: "161px",
        type:"timer2",
        ico: "el-icon-user-solid",
        show: true,
        tenantSiteCode: "test",
        styleCode: "GA191123A",
        craftNum: "HQFCF0001",
        craftCode: null,
        craftName: "前幅处理工艺一",
        basicCraftName: null,
        categoryCode: "C001",
        componentCode: "YB",
        componentName: "部件测试",
        deviceCode: "MDZ2",
        deviceName: "自动锁螺丝",
        materialMiddleclassCode: "XX0212",
        materialMiddleclassName: "灰黑色",
        toolCode1: "T001",
        toolCode2: "T002",
        toolCode3: "T003",
        toolName1: "T001",
        toolName2: "T002",
        toolName3: "T003",
        salaryLevelCode: "A",
        salaryLevelName: "一般工序",
        hourlyWage: 12.222,
        fabricCoefficient: 1.8,
        bundleTime: 16.3,
        deviceTmu: 12.2,
        artificialTmu: 20.2,
        deviceFloat: 2.3,
        artificialFloat: 5.4,
        manualDeviceTmu: 0,
        manualArtificialTmu: 0,
        bmSecond: 1.2,
        standardTimeTmu: 625.2,
        standardTimeSecond: 22.5,
        standardPrice: 4.581,
        workInstructions: "做工说明",
        qualityRequirements: "品质要求wwwwwwwwww",
        modifyTime: "2019-12-25 11:42:04",
        modifyUserId: "test",
        modifyUserName: "test"
      }
    ]
  }
];
